include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_single_quotes: true
    avoid_print: true
    sort_child_properties_last: true
    always_declare_return_types: true
    annotate_overrides: true
    unnecessary_this: true

analyzer:
  errors:
    depend_on_referenced_packages: ignore
  exclude:
    - build/**
    - "**/*.g.dart"
