name: bersih_laundry_app
description: "Bersih Laundry - Sistem Informasi Pemesanan dan Manajemen Laundry Kiloan"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Network / REST API
  http: ^1.6.0

  # Local database
  sqflite: ^2.3.3+1
  path: ^1.9.0
  path_provider: ^2.1.4

  # Session & preferences
  shared_preferences: ^2.2.3

  # Keamanan
  crypto: ^3.0.5

  # Notifikasi lokal
  flutter_local_notifications: ^17.2.2

  # Laporan pendapatan
  fl_chart: ^0.68.0

  # Cetak / bagikan nota
  pdf: ^3.11.1
  printing: ^5.13.2

  # Utilitas
  intl: ^0.19.0
  uuid: ^4.5.0
  equatable: ^2.0.5
  flutter_riverpod: ^2.6.1
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/